echo "Prefecture : hokkaido" > data/001_hokkaido/readme.md
echo "Prefecture : aomori" > data/002_aomori/readme.md
echo "Prefecture : iwate" > data/003_iwate/readme.md
echo "Prefecture : miyagi" > data/004_miyagi/readme.md
echo "Prefecture : akita" > data/005_akita/readme.md
echo "Prefecture : yamagata" > data/006_yamagata/readme.md
echo "Prefecture : fukushima" > data/007_fukushima/readme.md
echo "Prefecture : ibaraki" > data/008_ibaraki/readme.md
echo "Prefecture : tochigi" > data/009_tochigi/readme.md
echo "Prefecture : gunnma" > data/010_gunnma/readme.md
echo "Prefecture : saitama" > data/011_saitama/readme.md
echo "Prefecture : chiba" > data/012_chiba/readme.md
echo "Prefecture : tokyo" > data/013_tokyo/readme.md
echo "Prefecture : kanagawa" > data/014_kanagawa/readme.md
echo "Prefecture : niigata" > data/015_niigata/readme.md
echo "Prefecture : toyama" > data/016_toyama/readme.md
echo "Prefecture : ishikawa" > data/017_ishikawa/readme.md
echo "Prefecture : fukui" > data/018_fukui/readme.md
echo "Prefecture : yamanashi" > data/019_yamanashi/readme.md
echo "Prefecture : nagano" > data/020_nagano/readme.md
echo "Prefecture : gifu" > data/021_gifu/readme.md
echo "Prefecture : shizuoka" > data/022_shizuoka/readme.md
echo "Prefecture : aichi" > data/023_aichi/readme.md
echo "Prefecture : aichi" > data/023_aichi/readme.md
echo "Prefecture : aichi" > data/023_aichi/readme.md
echo "Prefecture : mie" > data/024_mie/readme.md
echo "Prefecture : shiga" > data/025_shiga/readme.md
echo "Prefecture : kyoto" > data/026_kyoto/readme.md
echo "Prefecture : osaka" > data/027_osaka/readme.md
echo "Prefecture : hyogo" > data/028_hyogo/readme.md
echo "Prefecture : nara" > data/029_nara/readme.md
echo "Prefecture : wakayama" > data/030_wakayama/readme.md
echo "Prefecture : tottori" > data/031_tottori/readme.md
echo "Prefecture : shimane" > data/032_shimane/readme.md
echo "Prefecture : okayama" > data/033_okayama/readme.md
echo "Prefecture : okayama" > data/033_okayama/readme.md
echo "Prefecture : hiroshima" > data/034_hiroshima/readme.md
echo "Prefecture : yamaguchi" > data/035_yamaguchi/readme.md
echo "Prefecture : tokushima" > data/036_tokushima/readme.md
echo "Prefecture : kagawa" > data/037_kagawa/readme.md
echo "Prefecture : kagawa" > data/037_kagawa/readme.md
echo "Prefecture : ehime" > data/038_ehime/readme.md
echo "Prefecture : kochi" > data/039_kochi/readme.md
echo "Prefecture : fukuoka" > data/040_fukuoka/readme.md
echo "Prefecture : saga" > data/041_saga/readme.md
echo "Prefecture : nagasaki" > data/042_nagasaki/readme.md
echo "Prefecture : kumamoto" > data/043_kumamoto/readme.md
echo "Prefecture : oita" > data/044_oita/readme.md
echo "Prefecture : miyazaki" > data/045_miyazaki/readme.md
echo "Prefecture : kagoshima" > data/046_kagoshima/readme.md
echo "Prefecture : okinawa" > data/047_okinawa/readme.md